services:
  jahia:
    image: jahia/jahia-discovery:latest
    ports:
      - "8080:8080"
    environment:
      EXECUTE_PROVISIONING_SCRIPT: "file:/mnt/jahia/provisioning.yml"
    volumes:
      - type: bind
        source: ./docker
        target: /mnt/jahia
    healthcheck:
      test: ["CMD", "curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://localhost:8080/start"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 90s
